name: Deploy Docker CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test_Build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore NuGet packages
      run: nuget restore github_docker_auto_deploy_test/github_docker_auto_deploy_test_TestProject/github_docker_auto_deploy_test_TestProject.csproj
    - name: Build the Solution
      run: msbuild github_docker_auto_deploy_test/github_docker_auto_deploy_test_TestProject/github_docker_auto_deploy_test_TestProject.csproj /p:Configuration=Release    
      
  
