name: Deploy Docker CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test_Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
    - uses: actions/checkout@v1
    - name: Build with dotnet
      working-directory: ./github_docker_auto_deploy_test
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./github_docker_auto_deploy_test
      run: dotnet test
  publish_to_docker:
    needs: Test_Build
    runs-on: ubuntu-latest
    steps:
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository:  hasansahinnn/testdeploy
        snapshot: true
  create_new_container:
    needs: publish_to_docker
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker rm -f $(docker ps -aq -f name=testdeploy)
          docker rmi $(docker images | grep 'hasansahinnn/testdeploy' | awk '{print $3}')
          docker pull hasansahinnn/testdeploy
          docker run --name testdeploy -p 5000:80 --restart=always -d hasansahinnn/testdeploy
      
  
